/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-07 03:48:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1690937569754L));
    _jspx_dependants.put("jar:file:/C:/workspace_teamPJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/after5duck/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspace_teamPJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/after5duck/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!DOCTYPE html>\r\n");
      out.write("            <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <title>회원가입</title>\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/signUp.css\">\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body>\r\n");
      out.write("            	<section class=\"logo\">\r\n");
      out.write("        			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            			<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/자른로고.png\" id=\"logo\">\r\n");
      out.write("        			</a>\r\n");
      out.write("    			</section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"signUp-content\">\r\n");
      out.write("                    <form action=\"signUp\" method=\"POST\" name=\"signUp-form\" onsubmit=\"return signUpValidate()\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"ddack\">딱 이것만 작성하면 가입 완료!</div>\r\n");
      out.write("                        <div class=\"ddack2\">\r\n");
      out.write("                            <div>*</div>는 필수입력 항목입니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- ============================= 아이디 영역 ============================== -->\r\n");
      out.write("                        <label for=\"memberId\">\r\n");
      out.write("                            <span class=\"required\">*</span>아이디\r\n");
      out.write("                        </label>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 아이디 입력 영역 -->\r\n");
      out.write("                        <div class=\"signUp-input-area\">\r\n");
      out.write("                            <input type=\"text\" id=\"memberId\" name=\"memberId\" placeholder=\"아이디\" maxlength=\"30\"\r\n");
      out.write("                                autocomplete=\"off\" required>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 아이디 메세지 -->\r\n");
      out.write("                        <span class=\"signUp-message\" id=\"idm\">영어/숫자 5~20글자 사이로 작성해주세요.</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- ============================= 비밀번호 영역 ================================ -->\r\n");
      out.write("                        <label for=\"memberPw\">\r\n");
      out.write("                            <span class=\"required\">*</span>비밀번호\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <!-- 비밀번호 입력 영역 -->\r\n");
      out.write("                        <div class=\"signUp-input-area\">\r\n");
      out.write("                            <input type=\"password\" id=\"memberPw\" name=\"memberPw\" placeholder=\"비밀번호\"\r\n");
      out.write("                                maxlength=\"30\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 비밀번호 확인 영역 -->\r\n");
      out.write("                        <div class=\"signUp-input-area\">\r\n");
      out.write("                            <input type=\"password\" id=\"memberPwConfirm\" placeholder=\"비밀번호 확인\"\r\n");
      out.write("                                maxlength=\"30\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 비번 메세지 -->\r\n");
      out.write("                        <span class=\"signUp-message\" id=\"pwm\">영어, 숫자, 특수문자(!,@,#,-,_) 6~30글자 사이로 작성해주세요.</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- ============================= 닉네임 영역 ============================== -->\r\n");
      out.write("                        <label for=\"memberNick\">\r\n");
      out.write("                            <span class=\"required\">*</span>닉네임\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <!-- 아이디 입력 영역 -->\r\n");
      out.write("                        <div class=\"signUp-input-area\">\r\n");
      out.write("                            <input type=\"text\" id=\"memberNick\" name=\"memberNick\" placeholder=\"닉네임\"\r\n");
      out.write("                                maxlength=\"30\" autocomplete=\"off\" required>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 닉네임 메세지 -->\r\n");
      out.write("                        <span class=\"signUp-message\" id=\"nickm\">영어/숫자/한글 2~10글자 사이로 작성해주세요.</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- =============================== 핸드폰 번호 영역 ============================= -->\r\n");
      out.write("                        <label for=\"memberTel\">\r\n");
      out.write("                            <span class=\"required\">*</span>핸드폰 번호\r\n");
      out.write("                        </label>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 핸드폰 번호 입력 영역 -->\r\n");
      out.write("                        <div class=\"signUp-input-area\">\r\n");
      out.write("                            <input type=\"text\" id=\"memberTel\" name=\"memberTel\" placeholder=\"핸드폰 번호 입력\"\r\n");
      out.write("                                autocomplete=\"off\" maxlength=\"11\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- <form action=\"sendSms\" method=\"post\"> -->\r\n");
      out.write("                                <!-- <button type=\"submit\">인증하기</button> -->\r\n");
      out.write("                            <!-- </form>  -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 핸드폰 메세지 -->\r\n");
      out.write("                        <span class=\"signUp-message\" id=\"telm\">전화번호를 입력해주세요( -제외)</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- ============================ 이메일 영역 =================================-->\r\n");
      out.write("                        <label for=\"memberEmail\">이메일</label>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 이메일 입력 영역 -->\r\n");
      out.write("                        <div class=\"signUp-input-area\">\r\n");
      out.write("                            <input type=\"email\" id=\"memberEmail\" name=\"memberEmail\" placeholder=\"이메일(선택 입력)\"\r\n");
      out.write("                                maxlength=\"30\" autocomplete=\"off\">\r\n");
      out.write("                            <button type=\"button\" id=\"emailBtn\">인증번호 발송</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 이메일 메세지 -->\r\n");
      out.write("                        <span class=\"signUp-message\" id=\"emailm\">메일을 받을 이메일을 입력해주세요.</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- 이메일 인증 영역 -->\r\n");
      out.write("                        <div class=\"signUp-input-area\">\r\n");
      out.write("                            <input type=\"text\" id=\"email2\" name=\"email2\" placeholder=\"인증번호 입력\" autocomplete=\"off\">\r\n");
      out.write("                            <button type=\"button\" id=\"email2Btn\">인증번호 확인</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 이메일 인증 메세지 -->\r\n");
      out.write("                        <span class=\"signUp-message\" id=\"emailm\">인증번호를 입력해주세요.</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <button id=\"btn\">버튼만 누르면 가입완료!</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("                <!-- 가입하기 버튼 -->\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\"\r\n");
      out.write("                    integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("\r\n");
      out.write("                    const contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("                </script>\r\n");
      out.write("\r\n");
      out.write("                <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/signUp.js\"></script>\r\n");
      out.write("\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/signUp.jsp(134,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sessionScope.message }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <script>\r\n");
          out.write("                        alert(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("\r\n");
          out.write("                    </script>\r\n");
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/member/signUp.jsp(140,20) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("message");
      // /WEB-INF/views/member/signUp.jsp(140,20) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
