/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-03 06:09:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUpAgree_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1690937569754L));
    _jspx_dependants.put("jar:file:/C:/workspace_teamPJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/after5duck/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspace_teamPJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/after5duck/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>약관동의</title>\r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/signUpAgree.css\">\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"https://kit.fontawesome.com/98acdabf0d.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/자른로고.png\" id=\"logo\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"signUp\" method=\"get\" name=\"signUpAgree-form\" onsubmit=\"return agreeValidate()\">\r\n");
      out.write("        <section class=\"container\">\r\n");
      out.write("\r\n");
      out.write("            <div style=\"font-size:45px; font-weight:bold; color: #000000;\">약관동의</div>\r\n");
      out.write("    \r\n");
      out.write("            <div>\r\n");
      out.write("                <!-- 전체동의 약관 박스 -->\r\n");
      out.write("                <input type=\"checkbox\"  id=\"check1\" class=\"cbox\" name=\"CHEBOX\" onclick=\"selectAll(this)\">\r\n");
      out.write("                <label for=\"check1\" style=\"font-size: xx-large;\">전체 약관에 동의합니다.</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"line1\" style=\"padding:0 40px\"></div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- 1 애니버스 이용약관 동의 -->\r\n");
      out.write("                <div class=\"smallContainer\">\r\n");
      out.write("                    <div class=\"one\">\r\n");
      out.write("                        <div><input type=\"checkbox\" id=\"check2\" name=\"CHEBOX\" class=\"req\" required></div>\r\n");
      out.write("                        <div><label>애니버스 이용약관 동의(필수)</label></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 약관 박스1 -->\r\n");
      out.write("                    <div class=\"agreeArea\">\r\n");
      out.write("                        <textarea id=\"agreeContent1\" readonly>\r\n");
      out.write("제 1 장 총칙\r\n");
      out.write("제 1 조 (목적)\r\n");
      out.write("본 약관은 애니버스 (이하 \"애니버스\")이 제공하는 모든 서비스(이하 \"서비스\")의 이용조건 및 절차, 이용자와 애니버스의 권리, 의무, 책임사항과 기타 제반 사항을 규정함을 목적으로 합니다.\r\n");
      out.write("\r\n");
      out.write("제 2 조 (약관의 명시와 개정)\r\n");
      out.write("1. 누리집은 이 약관의 내용과 주소지, 관리자의 성명, 개인정보보호 담당자의 성명, 연락처(전화, 팩스, 전자우편 주소 등) 등을 이용자가 알 수 있도록 누리집의 초기 서비스화면(전면)에 게시합니다.\r\n");
      out.write("2. 누리집은 약관의 규제에 관한 법률, 전자거래기본법, 전자서명법, 정보통신망 이용촉진 및 정보보호 등에 관한 법률 등 관련법을 위배하지 않는 범위에서 이 약관을 개정할 수 있습니다.\r\n");
      out.write("3. 누리집이 약관을 개정할 경우에는 적용일자 및 개정사유를 명시하여 현행약관과 함께 누리집의 초기화면에 그 적용일자 7일 이전부터 적용일자 전일 까지 공지합니다.\r\n");
      out.write("4. 이 약관에 동의하는 것은 정기적으로 웹을 방문하여 약관의 변경사항을 확인하는 것에 동의함을 의미합니다. 변경된 약관에 대한 정보를 알지 못해 발생하는 이용자의 피해는 누리집에서 책임지지 않습니다.\r\n");
      out.write("5. 회원은 변경된 약관에 동의하지 않을 경우 회원 탈퇴(해지)를 요청할 수 있으며, 변경된 약관의 효력 발생일로부터 7일 이후에도 거부의사를 표시하지 아니 하고 서비스를 계속 사용할 경우 약관의 변경 사항에 동의한 것으로 간주됩니다.\r\n");
      out.write("6. 본 약관에 명시되지 않은 사항은 전기통신기본법, 전기통신사업법, 정보통신망 이용촉진 및 정보보호 등에 관한 법률 및 기타 관련 법령의 규정에 의합니다.\r\n");
      out.write("제 3 조 (용어의 정의)\r\n");
      out.write("1. 본 약관에서 사용하는 용어의 정의는 다음과 같습니다.\r\n");
      out.write("① 이용계약: 서비스 이용과 관련하여 누리집과 이용자 간에 체결하는 계약\r\n");
      out.write("② 가입: 누리집이 제공하는 신청서 양식에 해당 정보를 기입하고, 본 약관에 동의하여 서비스 이용계약을 완료시키는 행위\r\n");
      out.write("③ 회원: 누리집에 회원가입에 필요한 개인 정보를 제공하여 회원 등록을 한 자로서, 누리집의 정보 및 서비스를 이용할 수 있는 자\r\n");
      out.write("④ 이용자번호(ID): 이용고객의 식별과 이용자가 서비스 이용을 위하여 이용자가 정하고 누리집이 승인하는 문자와 숫자의 조합\r\n");
      out.write("⑤ 비밀번호(PW): 이용자가 등록회원과 동일인인지 신원을 확인하고 통신상의 자신의 개인정보보호를 위하여 이용자 자신이 정한 문자와 숫자의 조합\r\n");
      out.write("⑥ 게시물: 회원이 서비스를 이용하면서 게시한 글, 이미지, 동영상 등 각종 파일과 링크 등\r\n");
      out.write("⑦ 탈퇴(해지): 서비스 또는 회원이 이용계약을 종료하는 행위\r\n");
      out.write("2. 본 약관에서 정의하지 않은 용어는 개별서비스에 대한 별도약관 및 이용규정에서 정의합니다.\r\n");
      out.write("제 2 장 이용계약의 성립 및 해지\r\n");
      out.write("제 4 조 (이용 계약의 성립)\r\n");
      out.write("1. 이용계약은 이용자가 본 이용약관 내용에 대한 동의와 이용신청에 대하여 누리집의 이용승낙으로 성립합니다.\r\n");
      out.write("2. 본 이용약관에 대한 동의는 이용신청 당시 해당 누리집의 '동의함' 버튼을 누름으로써 의사표시를 합니다.\r\n");
      out.write("제 5 조 (회원가입 및 탈퇴)\r\n");
      out.write("1. 회원가입은 신청자가 온라인으로 누리집에서 제공하는 소정의 가입신청 양식에서 요구하는 사항을 기록하여 가입을 완료하는 것으로 성립됩니다.\r\n");
      out.write("2. 누리집은 다음 각 호에 해당하는 회원에 대하여는 가입을 취소할 수 있습니다.\r\n");
      out.write("① 다른 사람의 명의를 사용하여 신청하였을 때\r\n");
      out.write("② 회원가입 신청서의 내용을 허위로 기재하였거나 신청하였을 때\r\n");
      out.write("③ 사회의 안녕 질서 혹은 미풍양속을 저해할 목적으로 신청하였을 때\r\n");
      out.write("④ 다른 사람의 누리집 서비스 이용을 방해하거나 그 정보를 도용하는 등의 행위를 하였을 때\r\n");
      out.write("⑤ 누리집을 이용하여 법령과 본 약관이 금지하는 행위를 하는 경우\r\n");
      out.write("⑥ 기타 누리집이 정한 회원가입 요건이 미비 되었을 때\r\n");
      out.write("3. 누리집은 다음 각 항에 해당하는 경우 그 사유가 해소될 때까지 이용계약 성립을 유보할 수 있습니다.\r\n");
      out.write("① 서비스 관련 제반 용량이 부족한 경우\r\n");
      out.write("② 기술상 장애 사유가 있는 경우\r\n");
      out.write("4. 누리집은 자체 개발하거나 다른 기관과 협의 등을 통해 일체의 서비스를 제공하며 변경 시 변경될 서비스의 내용을 이용자에게 공지하고 제공할 수 있습니다.\r\n");
      out.write("5. 회원은 등록사항에 변경이 있는 경우, 즉시 회원정보 수정 등 기타 방법으로 누리집에 대하여 그 변경사항을 알려야 합니다.\r\n");
      out.write("6. 회원은 가입 이후 누리집에서 제공하는 서비스를 제공받을 의사가 없는 등의 사유가 있을 경우에는 언제든지 회원탈퇴(해지)를 할 수 있습니다. 다만 타인에 의해 재 게시되거나, 게시판, 커뮤니티, 카페 등 공유 및 알림의 목적으로 등록된 게시물은 삭제되지 않으니 사전에 삭제 후 탈퇴하여야 합니다.\r\n");
      out.write("                        </textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 2 개인정보 동의 -->\r\n");
      out.write("                <div class=\"smallContainer\">\r\n");
      out.write("                    <div class=\"one\">\r\n");
      out.write("                        <div><input type=\"checkbox\" id=\"check3\" name=\"CHEBOX\" class=\"req\" required></div>\r\n");
      out.write("                        <div><label>개인정보 수집 및 이용에 대한 안내 (필수)</label></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 약관 박스2 -->\r\n");
      out.write("                    <div class=\"agreeArea\">\r\n");
      out.write("                        <textarea id=\"agreeContent2\" readonly>\r\n");
      out.write("1. 수집하는 개인정보 항목\r\n");
      out.write("문화체육관광부 대표 누리집의 이용자 참여와 이용통계 분석 등의 서비스를 위해 회원 가입시 아래의 개인정보를 수집하고 있습니다.\r\n");
      out.write("\r\n");
      out.write("가. 필수정보: 아이디, 이름, 성별, 출생년도, 비밀번호, 이메일\r\n");
      out.write("나. 서비스 이용 과정에서 아래와 같은 정보들이 자동으로 생성되어 수집될 수 있습니다.\r\n");
      out.write("(접속로그, 접속IP정보, 쿠키, 방문 일시, 서비스 이용기록, 불량 이용 기록)\r\n");
      out.write("2. 대표 누리집에서 이용자 회원가입 시 직접 개인정보를 입력 및 수정하여 개인정보를 수집합니다.\r\n");
      out.write("3. 수집 개인정보의 이용목적\r\n");
      out.write("회원가입, 회원활동 실적 관리, 회원탈퇴 의사 확인 등 회원관리\r\n");
      out.write("제공되는 서비스 이용에 관한 인구통계학적 분석, 서비스 방문 및 이용기록 분석, 관심사에 기반한 맞춤형 서비스 등 제공\r\n");
      out.write("신규 서비스 개발 및 활성화, 홍보 및 이벤트, 전자우편 서비스 등 정보 전달\r\n");
      out.write("향후 법정 대리인 본인확인, 분쟁 조정을 위한 기록보존, 불만처리 등 민원처리, 고지사항 전달 등\r\n");
      out.write("4. 개인정보의 보유 및 이용기간\r\n");
      out.write("이용자의 개인정보는 원칙적으로 개인정보의 수집 및 이용목적이 달성되면 지체 없이 파기합니다.\r\n");
      out.write("따라서 문화체육관광부 대표누리집은 최종 로그인 후 2년이 경과하였거나 정보주체의 회원 탈퇴 신청 시 회원의 개인정보를 지체 없이 파기합니다.\r\n");
      out.write("\r\n");
      out.write("동의 거부 권리 사실 및 불이익 내용\r\n");
      out.write("이용자는 동의를 거부할 권리가 있습니다. 동의를 거부할 경우에는 서비스 이용에 제한됨을 알려드립니다.\r\n");
      out.write("                        </textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 3 이벤트 동의 -->\r\n");
      out.write("                <div class=\"smallContainer\">\r\n");
      out.write("                    <div class=\"one\">\r\n");
      out.write("                        <div><input type=\"checkbox\" id=\"check4\" name=\"CHEBOX\"></div>\r\n");
      out.write("                        <div><label>이벤트 소식 메일 수신(선택)</label></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 약관 박스3 -->\r\n");
      out.write("                    <div class=\"agreeArea\">\r\n");
      out.write("                        <textarea id=\"agreeContent3\" readonly>\r\n");
      out.write("본 광고 서비스 이용약관(이하 “본 약관”이라 합니다)은 애니버스(이하 “회사”)가 \r\n");
      out.write("제공하는 서비스를 통하여 상품을 등록하고 펀딩을 통해 자금을 모으거나 또는 \r\n");
      out.write("판매하는 자(이하 “메이커”라 합니다)가 본 서비스를 제공하는 회사가 \r\n");
      out.write("운영 및 제공하는 인터넷 사이트(https://www.wadiz.kr, 이하 “사이트”라 합니다), \r\n");
      out.write("모바일 애플리케이션 또는 모바일 웹에서 광고/마케팅 상품을 매수하여 \r\n");
      out.write("이를 시행함에 있어 회사와 메이커 간의 권리, \r\n");
      out.write("의무 등 필요한 제반 사항을 규정함을 목적으로 합니다.\r\n");
      out.write("                        </textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <!-- 다음 단계로 가기 버튼 -->\r\n");
      out.write("            <button id=\"btn\">다음 단계로 가기</button>\r\n");
      out.write("    \r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/signUpAgree.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/signUpAgree.jsp(155,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sessionScope.message }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<script>\r\n");
          out.write("			alert(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("			\r\n");
          out.write("		</script>\r\n");
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/member/signUpAgree.jsp(161,2) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("message");
      // /WEB-INF/views/member/signUpAgree.jsp(161,2) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
